apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: linera-admin
  serviceMonitorSelector:
    matchLabels:
      team: infra
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false